=== superfluidity/RDCL3D/lib/etsi/schemas/vnfd_old.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "vendor": {
      "type": "string"
    },
    "descriptor_version": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "vdu": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "computation_requirement": {
            "type": "string"
          },
          "virtual_memory_resource_element": {
            "type": "string"
          },
          "virtual_network_bandwidth_resource": {
            "type": "string"
          },
          "vnfc": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "connection_point": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "virtual_link_reference": {
                        "type": "string"
                      },
                      "type": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "virtual_link_reference",
                      "type"
                    ]
                  }
                }
              },
              "required": [
                "id",
                "connection_point"
              ]
            }
          }
        },
        "required": [
          "id",
          "computation_requirement",
          "virtual_memory_resource_element",
          "virtual_network_bandwidth_resource",
          "vnfc"
        ]
      }
    },
    "virtual_link": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "connectivity_type": {
            "type": "string"
          },
          "connection_points_references": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "root_requirement": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "connectivity_type",
          "connection_points_references",
          "root_requirement"
        ]
      }
    },
    "connection_point": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "virtual_link_reference": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "type",
          "virtual_link_reference"
        ]
      }
    }
  },
  "required": [
    "id",
    "vendor",
    "descriptor_version",
    "version",
    "vdu",
    "virtual_link",
    "connection_point"
  ]
}

=== superfluidity/RDCL3D/sf_dev/examples/my_example/JSON/VNFD/vnf2.json
{
  "id": "vnf2",
  "vendor": "netgroup",
  "descriptor_version": "0.1",
  "version": "0.1",

  "vdu": [
    {
      "id": "vdu21",
      "computation_requirement": "",
      "virtual_memory_resource_element": "",
      "virtual_network_bandwidth_resource": "",
      "vnfc": [
        {
          "id": "vnfc21",
          "connection_point": [
            {
              "id": "cp22",
              "virtual_link_reference": "vl21",
              "type": "NIC"
            }
          ]

        },
        {
          "id": "vnfc22",
          "connection_point": [
            {
              "id": "cp23",
              "virtual_link_reference": "vl21",
              "type": "NIC"
            }
          ]

        },
        {
          "id": "vnfc23",
          "connection_point": [
            {
              "id": "cp24",
              "virtual_link_reference": "vl21",
              "type": "NIC"
            }
          ]

        }
      ]
    }
  ],
  "virtual_link": [{
      "id": "vl21",
      "connectivity_type": " E-Line",
      "connection_points_references": [
        "cp21",
        "cp22",
        "cp23",
        "cp24"
      ],
      "root_requirement": ""

    }
  ],
  "connection_point": [
    {
      "id": "cp21",
      "type": "",
      "virtual_link_reference": "vl21"
    }
  ]
}
