=== superfluidity/RDCL3D/lib/etsi/schemas/vnffgd.json
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "http://jsonschema.net",
	"required":true,
	"properties":{
		"connection_point": {
			"type":"array",
			"id": "http://jsonschema.net/connection_point",
			"required":true,
			"items": {
				"type":"string",
				"id": "http://jsonschema.net/connection_point/0",
				"required": true
			}
		},
		"constituent_vnfs": {
			"type":"array",
			"id": "http://jsonschema.net/constituent_vnfs",
			"required":true,
			"items": {
				"type":"string",
				"id": "http://jsonschema.net/constituent_vnfs/0",
				"required":true
			}

		},
		"dependent_virtual_link": {
			"type":"array",
			"id": "http://jsonschema.net/dependent_virtual_link",
			"required":true,
			"items": {
					"type": "string",
					"id": "http://jsonschema.net/dependent_virtual_link/0",
					"required":true
			}


		},
		"descriptor_version": {
			"type":"string",
			"id": "http://jsonschema.net/descriptor_version",
			"required":true
		},
		"id": {
			"type":"string",
			"id": "http://jsonschema.net/id",
			"required":true
		},
		"network_forwarding_path": {
			"type":"array",
			"id": "http://jsonschema.net/network_forwarding_path",
			"required":true,
			"items":
				{
					"type":"object",
					"id": "http://jsonschema.net/network_forwarding_path/0",
					"required":true,
					"properties":{
						"connection": {
							"type":"array",
							"id": "http://jsonschema.net/network_forwarding_path/0/connection",
							"required":true,
							"items":
								{
									"type":"array",
									"id": "http://jsonschema.net/network_forwarding_path/0/connection/0",
									"required":true
								}


						},
						"id": {
							"type":"string",
							"id": "http://jsonschema.net/network_forwarding_path/0/id",
							"required":true
						},
						"policy": {
							"type":"string",
							"id": "http://jsonschema.net/network_forwarding_path/0/policy",
							"required":true
						}
					}
				}


		},
		"number_of_endpoints": {
			"type":"number",
			"id": "http://jsonschema.net/number_of_endpoints",
			"required":true
		},
		"number_of_virtual_links": {
			"type":"number",
			"id": "http://jsonschema.net/number_of_virtual_links",
			"required":true
		},
		"vendor": {
			"type":"string",
			"id": "http://jsonschema.net/vendor",
			"required":true
		},
		"version": {
			"type":"string",
			"id": "http://jsonschema.net/version",
			"required":true
		},
		"vnffgd_security": {
			"type":"string",
			"id": "http://jsonschema.net/vnffgd_security",
			"required":true
		}
	}
}

=== superfluidity/RDCL3D/sf_dev/examples/my_example/JSON/VNFFGD/vnffg1.json
{
  "id": "vnffg1",
  "vendor": "netgroup",
  "descriptor_version": "0.1",
  "version": "0.1",
  "number_of_endpoints": 8 ,
  "number_of_virtual_links": 5 ,
  "dependent_virtual_link": [
    "vl01",
    "vl11",
    "vl02",
    "vl31",
    "vl04"
  ],
  "network_forwarding_path": [
    {
      "id": "nfp1",
      "policy": "A policy or rule to apply to the NFP",
      "connection": [
        [0, "cp01"],
        [1, "cp11"],
        [2, "cp14"],
        [3, "cp13"],
        [4, "cp31"],
        [5, "cp33"],
        [6, "cp03"]
      ]
    }
  ] ,
  "connection_point":[
    "cp01",
    "cp11",
    "cp14",
    "cp13",
    "cp31",
    "cp33",
    "cp03"
  ] ,
  "constituent_vnfs":[
    "vnf1",
    "vnf3"
  ],
  "vnffgd_security": "signature"
}
